# Generated by Django 5.2.8 on 2026-03-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(verbose_name='Date')),
                ('comment_text', models.CharField(max_length=1000)),
            ],
        ),
    ]
